CREATE DATABASE IF NOT EXISTS medium_city;
USE medium_city;
CREATE TABLE IF NOT EXISTS player (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` CHAR(128) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS city (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`player_id`  BIGINT UNSIGNED NOT NULL,
	name  CHAR(128) NOT NULL, 
	coordinate_x TINYINT UNSIGNED NOT NULL,
	coordinate_y TINYINT UNSIGNED NOT NULL,
	`type` TINYINT UNSIGNED NOT NULL,
	tax_rate FLOAT UNSIGNED NOT NULL,
	gold INT UNSIGNED NOT NULL DEFAULT '0',
	food INT UNSIGNED NOT NULL DEFAULT '0',
	population INT UNSIGNED NOT NULL DEFAULT '0',
	time_at_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	time_at_last_tax TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	time_at_last_food TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`),
	KEY (`player_id`, `type`),
	CONSTRAINT `player_id` FOREIGN KEY (`player_id`) REFERENCES player(`id`) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS soldier_batch (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`city_id` BIGINT UNSIGNED NOT NULL,
	`num` INT UNSIGNED NOT NULL,
	`soldier_type` TINYINT UNSIGNED NOT NULL,
	`state` TINYINT UNSIGNED NOT NULL,
	time_at_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	time_at_training TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`),
	KEY (`city_id`,`state`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS soldiers (
	`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`city_id` BIGINT UNSIGNED NOT NULL,
	`num` INT UNSIGNED NOT NULL,
	`soldier_type` TINYINT UNSIGNED NOT NULL,
	time_at_last_eating TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`),
	KEY (`city_id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
